= Service Poller

image:https://img.shields.io/badge/Java-11-success[]
image:https://img.shields.io/badge/vert.x-4.2.1-purple.svg[link="https://vertx.io"]

== Description

The Service Poller is a monitoring tools that we can check our service's status. We check the status of any URL by HTTP GET request and store as *OK* (success response) and *FAIL* (unavailable). All services with their status are visualized in a table with multiple functionality regarding Creating, Updating and Delete.

== Getting started
These instructions will get you through the bootstrap phase of creating and deploying samples of containerized applications with Docker Compose.

=== Prerequisites

- Make sure that you have Docker and Docker Compose installed
- Windows or macOS:
[Install Docker Desktop](https://www.docker.com/get-started)
- Linux: [Install Docker](https://www.docker.com/get-started) and then
[Docker Compose](https://github.com/docker/compose)

== Configuration

You can change the database properties like host, port and credential from `application.properties`:
```
datasource.host=
datasource.port=
datasource.database=
datasource.username=
datasource.password=
```

By default to connect application to the database started by docker-compose on same network with application the port has been set *3306*.

== Running

The root directory project contains the `docker-compose.yaml` which
describes the configuration of service components includes main *Service Poller* and the database (MySQL).

```console
docker-compose up -d
```

Access in web:

```
http://localhost:8080
```

Login from web with these 2 users:

User 1:
```
username: user1
password: password1
```

User 2:
```
username: user2
password: password2
```
